apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: application
resources:
  - namespace.yaml
  - shared-secrets.yaml
  - userservice
  - productservice
  - orderservice
  - paymentservice
  - notificationservice