apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-handler
  labels:
    app: productservice-handler
    component: handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productservice-handler
  template:
    metadata:
      labels:
        app: productservice-handler
        component: handler
    spec:
      containers:
        - name: message-handler
          image: productservice:latest
          imagePullPolicy: Never
          command: ["/app/productservice", "message-handler"]
          env:
            - name: PRODUCT_HTTP_ADDRESS
              value: ":8083"
            - name: PRODUCT_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: PRODUCT_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: productservice-db-secret
                  key: DB_NAME
            - name: PRODUCT_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: productservice-db-secret
                  key: DB_USER
            - name: PRODUCT_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: productservice-db-secret
                  key: DB_PASSWORD
            - name: PRODUCT_AMQP_HOST
              value: rabbitmq.infrastructure.svc.cluster.local:5672
            - name: PRODUCT_AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-app-secret
                  key: AMQP_USER
            - name: PRODUCT_AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-app-secret
                  key: AMQP_PASSWORD