apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-handler
  labels:
    app: userservice-handler
    component: handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice-handler
  template:
    metadata:
      labels:
        app: userservice-handler
        component: handler
    spec:
      containers:
        - name: message-handler
          image: userservice:latest
          imagePullPolicy: Never
          command: ["/app/userservice", "message-handler"]
          env:
            - name: USER_HTTP_ADDRESS
              value: ":8083"
            - name: USER_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: USER_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: userservice-db-secret
                  key: DB_NAME
            - name: USER_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: userservice-db-secret
                  key: DB_USER
            - name: USER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: userservice-db-secret
                  key: DB_PASSWORD
            - name: USER_AMQP_HOST
              value: rabbitmq.infrastructure.svc.cluster.local:5672
            - name: USER_AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-app-secret
                  key: AMQP_USER
            - name: USER_AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-app-secret
                  key: AMQP_PASSWORD
            - name: USER_TEMPORAL_HOST
              value: temporal.infrastructure.svc.cluster.local:7233