services:
  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  userservice:
    container_name: userservice
    build:
      context: ./rp-userservice-main
      dockerfile: Dockerfile
    command:
      - service
    ports:
      - "8081:8081"
    environment:
      USER_DATABASE_HOST: userservice-db
      USER_DATABASE_NAME: userservice_db
      USER_DATABASE_USER: userservice
      USER_DATABASE_PASSWORD: 12345Q
    depends_on:
      userservice-db:
        condition: service_healthy

  userservice-workflow-worker:
    container_name: userservice-workflow-worker
    build:
      context: ./rp-userservice-main
      dockerfile: Dockerfile
    command:
      - workflow-worker
    environment:
      USER_DATABASE_HOST: userservice-db
      USER_DATABASE_NAME: userservice_db
      USER_DATABASE_USER: userservice
      USER_DATABASE_PASSWORD: 12345Q
      USER_TEMPORAL_HOST: userservice-temporal:7233
    depends_on:
      userservice-db:
        condition: service_healthy
      userservice-temporal:
        condition: service_started

  userservice-message-handler:
    container_name: userservice-message-handler
    build:
      context: ./rp-userservice-main
      dockerfile: Dockerfile
    command:
      - message-handler
    environment:
      USER_DATABASE_HOST: userservice-db
      USER_DATABASE_NAME: userservice_db
      USER_DATABASE_USER: userservice
      USER_DATABASE_PASSWORD: 12345Q

      USER_AMQP_HOST: userservice-rmq
      USER_AMQP_USER: guest
      USER_AMQP_PASSWORD: guest
      USER_TEMPORAL_HOST: userservice-temporal:7233
    depends_on:
      userservice-db:
        condition: service_healthy
      userservice-rmq:
        condition: service_healthy
      userservice-temporal:
        condition: service_started

  productservice:
    build:
      context: ./rp-productservice
    container_name: productservice
    command:
      - service
    ports:
      - "8083:8081"
      - "8084:8082"
    environment:
      PRODUCT_DATABASE_HOST: productservice-db
      PRODUCT_DATABASE_NAME: productservice_db
      PRODUCT_DATABASE_USER: productservice
      PRODUCT_DATABASE_PASSWORD: 12345Q
    depends_on:
      productservice-db:
        condition: service_healthy

  productservice-message-handler:
    build:
      context: ./rp-productservice
    container_name: productservice-message-handler
    command:
      - message-handler
    environment:
      PRODUCT_DATABASE_HOST: productservice-db
      PRODUCT_DATABASE_NAME: productservice_db
      PRODUCT_DATABASE_USER: productservice
      PRODUCT_DATABASE_PASSWORD: 12345Q
      PRODUCT_AMQP_HOST: userservice-rmq
      PRODUCT_AMQP_USER: guest
      PRODUCT_AMQP_PASSWORD: guest
    depends_on:
      productservice-db:
        condition: service_healthy
      userservice-rmq:
        condition: service_healthy

  paymentservice:
    build:
      context: ./rp-paymentservice
    container_name: paymentservice
    command:
      - service
    ports:
      - "8085:8081"
      - "8092:8082"
    environment:
      PAYMENT_DATABASE_HOST: paymentservice-db
      PAYMENT_DATABASE_NAME: paymentservice_db
      PAYMENT_DATABASE_USER: paymentservice
      PAYMENT_DATABASE_PASSWORD: 12345Q
    depends_on:
      paymentservice-db:
        condition: service_healthy

  paymentservice-message-handler:
    build:
      context: ./rp-paymentservice
    container_name: paymentservice-message-handler
    command:
      - message-handler
    environment:
      PAYMENT_DATABASE_HOST: paymentservice-db
      PAYMENT_DATABASE_NAME: paymentservice_db
      PAYMENT_DATABASE_USER: paymentservice
      PAYMENT_DATABASE_PASSWORD: 12345Q
      PAYMENT_AMQP_HOST: userservice-rmq
      PAYMENT_AMQP_USER: guest
      PAYMENT_AMQP_PASSWORD: guest
    depends_on:
      paymentservice-db:
        condition: service_healthy
      userservice-rmq:
        condition: service_healthy

  orderservice:
    build:
      context: ./rp-orderservice
    container_name: orderservice
    command:
      - service
    ports:
      - "8091:8081"
      - "8088:8082"
    environment:
      ORDER_DATABASE_HOST: orderservice-db
      ORDER_DATABASE_NAME: orderservice_db
      ORDER_DATABASE_USER: orderservice
      ORDER_DATABASE_PASSWORD: 12345Q
    depends_on:
      orderservice-db:
        condition: service_healthy

  orderservice-message-handler:
    build:
      context: ./rp-orderservice
    container_name: orderservice-message-handler
    command:
      - message-handler
    environment:
      ORDER_DATABASE_HOST: orderservice-db
      ORDER_DATABASE_NAME: orderservice_db
      ORDER_DATABASE_USER: orderservice
      ORDER_DATABASE_PASSWORD: 12345Q
      ORDER_AMQP_HOST: userservice-rmq
      ORDER_AMQP_USER: guest
      ORDER_AMQP_PASSWORD: guest
    depends_on:
      orderservice-db:
        condition: service_healthy
      userservice-rmq:
        condition: service_healthy

  notificationservice:
    build:
      context: ./rp-notificationservice
    container_name: notificationservice
    command:
      - service
    ports:
      - "8089:8081"
      - "8090:8082"
    environment:
      NOTIFICATION_DATABASE_HOST: notificationservice-db
      NOTIFICATION_DATABASE_NAME: notificationservice_db
      NOTIFICATION_DATABASE_USER: notificationservice
      NOTIFICATION_DATABASE_PASSWORD: 12345Q
    depends_on:
      notificationservice-db:
        condition: service_healthy

  notificationservice-message-handler:
    build:
      context: ./rp-notificationservice
    container_name: notificationservice-message-handler
    command:
      - message-handler
    environment:
      NOTIFICATION_DATABASE_HOST: notificationservice-db
      NOTIFICATION_DATABASE_NAME: notificationservice_db
      NOTIFICATION_DATABASE_USER: notificationservice
      NOTIFICATION_DATABASE_PASSWORD: 12345Q
      NOTIFICATION_AMQP_HOST: userservice-rmq
      NOTIFICATION_AMQP_USER: guest
      NOTIFICATION_AMQP_PASSWORD: guest
    depends_on:
      notificationservice-db:
        condition: service_healthy
      userservice-rmq:
        condition: service_healthy

  userservice-db:
    image: "mysql:8.3"
    container_name: userservice-db
    command: [ "--max_connections=100" ]
    volumes:
      - "userservice-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: userservice_db
      MYSQL_USER: userservice
      MYSQL_PASSWORD: 12345Q
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s

  productservice-db:
    image: "mysql:8.3"
    container_name: productservice-db
    command: [ "--max_connections=100" ]
    volumes:
      - "productservice-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: productservice_db
      MYSQL_USER: productservice
      MYSQL_PASSWORD: 12345Q
    ports:
      - "3307:3306"
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s

  paymentservice-db:
    image: "mysql:8.3"
    container_name: paymentservice-db
    command: [ "--max_connections=100" ]
    volumes:
      - "paymentservice-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: paymentservice_db
      MYSQL_USER: paymentservice
      MYSQL_PASSWORD: 12345Q
    ports:
      - "3308:3306"
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s

  orderservice-db:
    image: "mysql:8.3"
    container_name: orderservice-db
    command: [ "--max_connections=100" ]
    volumes:
      - "orderservice-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: orderservice_db
      MYSQL_USER: orderservice
      MYSQL_PASSWORD: 12345Q
    ports:
      - "3309:3306"
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s

  notificationservice-db:
    image: "mysql:8.3"
    container_name: notificationservice-db
    command: [ "--max_connections=100" ]
    volumes:
      - "notificationservice-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: notificationservice_db
      MYSQL_USER: notificationservice
      MYSQL_PASSWORD: 12345Q
    ports:
      - "3310:3306"
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s

  userservice-rmq:
    image: "rabbitmq:4.2.0-management-alpine"
    container_name: userservice-rmq
    hostname: userservice-rmq
    ports:
      - "5673:5672"
      - "15672:15672"
    volumes:
      - "userservice-rmq-data:/var/lib/rabbitmq"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s

  userservice-temporal:
    container_name: userservice-temporal
    depends_on:
      userservice-db:
        condition: service_healthy
    environment:
      - DB=mysql8
      - DB_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PWD=
      - MYSQL_SEEDS=userservice-db
      - TEMPORAL_ADDRESS=userservice-temporal:7233
      - TEMPORAL_CLI_ADDRESS=userservice-temporal:7233
    image: temporalio/auto-setup:1.29.1
    ports:
      - 7233:7233

  userservice-temporal-admin-tools:
    container_name: userservice-temporal-admin-tools
    depends_on:
      - userservice-temporal
    environment:
      - TEMPORAL_ADDRESS=userservice-temporal:7233
      - TEMPORAL_CLI_ADDRESS=userservice-temporal:7233
    image: temporalio/admin-tools:1.29.1-tctl-1.18.4-cli-1.5.0
    stdin_open: true
    tty: true

  userservice-temporal-ui:
    container_name: userservice-temporal-ui
    depends_on:
      - userservice-temporal
    environment:
      - TEMPORAL_ADDRESS=userservice-temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.34.0
    ports:
      - 8080:8080

volumes:
  userservice-db-data:
  productservice-db-data:
  paymentservice-db-data:
  orderservice-db-data:
  notificationservice-db-data:
  userservice-rmq-data: