global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'orderservice'
    static_configs:
      - targets: ['orderservice:8082', 'orderservice-message-handler:8082']

  - job_name: 'paymentservice'
    static_configs:
      - targets: ['paymentservice:8082', 'paymentservice-message-handler:8082']

  - job_name: 'productservice'
    static_configs:
      - targets: ['productservice:8082', 'productservice-message-handler:8082']

  - job_name: 'userservice'
    static_configs:
      - targets: ['userservice:8082', 'userservice-message-handler:8082']

  - job_name: 'notificationservice'
    static_configs:
      - targets: ['notificationservice:8082', 'notificationservice-message-handler:8082']