services:
  orderservice:
    image: orderservice
    container_name: orderservice
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - service
    ports:
      - "8081:8081"
      - "8088:8082"
    environment:
      ORDER_DATABASE_HOST: orderservice-db
      ORDER_DATABASE_NAME: orderservice_db
      ORDER_DATABASE_USER: orderservice
      ORDER_DATABASE_PASSWORD: 12345Q
    depends_on:
      orderservice-db:
        condition: service_healthy

  orderservice-message-handler:
    image: orderservice
    container_name: orderservice-message-handler
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - message-handler
    environment:
      ORDER_DATABASE_HOST: orderservice-db
      ORDER_DATABASE_NAME: orderservice_db
      ORDER_DATABASE_USER: orderservice
      ORDER_DATABASE_PASSWORD: 12345Q

      ORDER_AMQP_HOST: userservice-rmq
      ORDER_AMQP_USER: guest
      ORDER_AMQP_PASSWORD: guest
    depends_on:
      orderservice-db:
        condition: service_healthy
      userservice-rmq:
        condition: service_healthy

  orderservice-db:
    image: "mysql:8.3"
    container_name: orderservice-db
    command: [ "--max_connections=100" ]
    volumes:
      - "orderservice-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: orderservice_db
      MYSQL_USER: orderservice
      MYSQL_PASSWORD: 12345Q
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost --silent"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s


  userservice-rmq:
    image: "rabbitmq:4.2.0-management-alpine"
    container_name: userservice-rmq
    hostname: userservice-rmq
    ports:
      - "15672:15672"
    volumes:
      - "userservice-rmq-data:/var/lib/rabbitmq/mnesia"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      timeout: 3s
      retries: 30
    depends_on:
      orderservice-db:
        condition: service_healthy
      userservice-rmq:
        condition: service_healthy


volumes:
  orderservice-db-data:
  userservice-rmq-data: