apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-handler
  labels:
    app: paymentservice-handler
    component: handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice-handler
  template:
    metadata:
      labels:
        app: paymentservice-handler
        component: handler
    spec:
      containers:
        - name: message-handler
          image: paymentservice:latest
          imagePullPolicy: Never
          command: ["/app/paymentservice", "message-handler"]
          env:
            - name: PAYMENT_HTTP_ADDRESS
              value: ":8083"
            - name: PAYMENT_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: PAYMENT_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: paymentservice-db-secret
                  key: DB_NAME
            - name: PAYMENT_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: paymentservice-db-secret
                  key: DB_USER
            - name: PAYMENT_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paymentservice-db-secret
                  key: DB_PASSWORD
            - name: PAYMENT_AMQP_HOST
              value: rabbitmq.infrastructure.svc.cluster.local:5672
            - name: PAYMENT_AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-app-secret
                  key: AMQP_USER
            - name: PAYMENT_AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-app-secret
                  key: AMQP_PASSWORD