apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-db
type: Opaque
stringData:
  DB_NAME: "userservice_db"
  DB_USER: "userservice"
  DB_PASSWORD: "12345Q"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-product-db
type: Opaque
stringData:
  DB_NAME: "productservice_db"
  DB_USER: "productservice"
  DB_PASSWORD: "12345Q"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-order-db
type: Opaque
stringData:
  DB_NAME: "orderservice_db"
  DB_USER: "orderservice"
  DB_PASSWORD: "12345Q"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-payment-db
type: Opaque
stringData:
  DB_NAME: "paymentservice_db"
  DB_USER: "paymentservice"
  DB_PASSWORD: "12345Q"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-notification-db
type: Opaque
stringData:
  DB_NAME: "notificationservice_db"
  DB_USER: "notificationservice"
  DB_PASSWORD: "12345Q"