services:
  paymentservice:
    image: paymentservice
    container_name: paymentservice
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - service
    ports:
      - "8085:8081"
      - "8082:8082"
    environment:
      PAYMENT_DATABASE_HOST: paymentservice-db
      PAYMENT_DATABASE_NAME: paymentservice_db
      PAYMENT_DATABASE_USER: paymentservice
      PAYMENT_DATABASE_PASSWORD: 12345Q
    depends_on:
      paymentservice-db:
        condition: service_healthy

  paymentservice-message-handler:
    image: paymentservice
    container_name: paymentservice-message-handler
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - message-handler
    environment:
      PAYMENT_DATABASE_HOST: paymentservice-db
      PAYMENT_DATABASE_NAME: paymentservice_db
      PAYMENT_DATABASE_USER: paymentservice
      PAYMENT_DATABASE_PASSWORD: 12345Q

      PAYMENT_AMQP_HOST: userservice-rmq
      PAYMENT_AMQP_USER: guest
      PAYMENT_AMQP_PASSWORD: guest
    depends_on:
      paymentservice-db:
        condition: service_healthy
      userservice-rmq:
        condition: service_healthy

  paymentservice-db:
    image: "mysql:8.3"
    container_name: paymentservice-db
    command: [ "--max_connections=100" ]
    volumes:
      - "paymentservice-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: paymentservice_db
      MYSQL_USER: paymentservice
      MYSQL_PASSWORD: 12345Q
    ports:
      - "3308:3306"
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s

  userservice-rmq:
    image: "rabbitmq:4.2.0-management-alpine"
    container_name: userservice-rmq
    hostname: userservice-rmq
    ports:
      - "15672:15672"
    volumes:
      - "userservice-rmq-data:/var/lib/rabbitmq/mnesia"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  paymentservice-db-data:
  userservice-rmq-data: